/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllDayBannerRow: typeof import('./src/components/AllDayBannerRow.vue')['default']
    AppTimeField: typeof import('./src/components/AppTimeField.vue')['default']
    CalendarDayView: typeof import('./src/components/CalendarDayView.vue')['default']
    CalendarMonthView: typeof import('./src/components/CalendarMonthView.vue')['default']
    CalendarToolbar: typeof import('./src/components/CalendarToolbar.vue')['default']
    CalendarWeekView: typeof import('./src/components/CalendarWeekView.vue')['default']
    CalendarYearView: typeof import('./src/components/CalendarYearView.vue')['default']
    CountdownBanner: typeof import('./src/components/CountdownBanner.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/DeleteConfirmDialog.vue')['default']
    EventBlock: typeof import('./src/components/EventBlock.vue')['default']
    EventDialog: typeof import('./src/components/EventDialog.vue')['default']
    EventFormFields: typeof import('./src/components/EventFormFields.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconPickerDialog: typeof import('./src/components/IconPickerDialog.vue')['default']
    KeyboardShortcutsDialog: typeof import('./src/components/KeyboardShortcutsDialog.vue')['default']
    PersonFilterBar: typeof import('./src/components/PersonFilterBar.vue')['default']
    PinnedEventsStrip: typeof import('./src/components/PinnedEventsStrip.vue')['default']
    RecurrenceSelector: typeof import('./src/components/RecurrenceSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SubTaskEditor: typeof import('./src/components/SubTaskEditor.vue')['default']
    TaskView: typeof import('./src/components/TaskView.vue')['default']
    TimeGrid: typeof import('./src/components/TimeGrid.vue')['default']
    TimeTimerDisplay: typeof import('./src/components/TimeTimerDisplay.vue')['default']
    UpNextView: typeof import('./src/components/UpNextView.vue')['default']
  }
}
